market/cart/urls.py
from django.urls import path
from .views import (
    CartView,
    AddCartFromProduct,
    RemoveOneCartView,
)

app_name = "cart"

urlpatterns = [
    path("", CartView.as_view(), name="user_cart"),
    path("add", AddCartFromProduct.as_view(), name="add_cart"),
    path("delete", RemoveOneCartView.as_view(), name="delete_cart"),
]

market/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path("settings/", include("site_settings.urls")),
    path("api/", include("api_payments.urls")),
]

urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path("", include("products.urls")),
    path("profiles/", include("profiles.urls")),
    path("shops/", include("shops.urls")),
    path("catalog/", include("catalog.urls")),
    path("cart/", include("cart.urls")),
    path("comparison/", include("comparison.urls")),
    path("pay/", include("payapp.urls")),
    path("orders/", include("orders.urls")),
    path("importdata/", include("importdata.urls")),
    path("discounts/", include("discount.urls")),
)

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS))

market/profiles/urls.py
from django.urls import path
from .views import (
    HomePage,
    CustomLoginView,
    AboutUserView,
    UserLogoutView,
    UserRegisterView,
    UserResetPasswordView,
    UserUpdateProfileInfo,
    UserHistoryView,
    CustomPasswordResetView,
    CustomPasswordResetDoneView,
    CustomPasswordResetConfirmView,
    CustomPasswordResetCompleteView,
)

app_name = "profiles"

urlpatterns = [
    path("", HomePage.as_view(), name="home-page"),
    path(
        "login/",
        CustomLoginView.as_view(
            template_name="profiles/login.jinja2",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("about-user/", AboutUserView.as_view(), name="about-user"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("change_password/", UserResetPasswordView.as_view(), name="change-password"),
    path("update_info/<int:pk>/", UserUpdateProfileInfo.as_view(), name="update-info"),
    path("history/", UserHistoryView.as_view(), name="browsing_history"),
    path("reset_password/1", CustomPasswordResetView.as_view(), name="reset_password"),
    path("reset_password/2", CustomPasswordResetDoneView.as_view(), name="reset_password_done"),
    path("reset_password/<uidb64>/<token>", CustomPasswordResetConfirmView.as_view(), name="reset_password_confirm"),
    path("reset_password_complete/", CustomPasswordResetCompleteView.as_view(), name="reset_password_complete"),
]

market/profiles/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.core.validators import RegexValidator


def profile_directory_path(instance: "User", filename):
    return "profiles/{pk}/avatar/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class User(AbstractUser, PermissionsMixin):
    email = models.EmailField(_("email address"), unique=True)
    phone = models.CharField(
        _("Номер телефона"),
        default="",
        validators=[
            RegexValidator(regex=r"\+[7]\([0-9]{3}\)[0-9]{3}\-[0-9]{2}\-[0-9]{2}", message=_("номер некорректный"))
        ],
    )
    residence = models.CharField(
        _("Город проживания"),
        max_length=100,
    )
    address = models.TextField(_("Адрес"), max_length=500, blank=True)
    avatar = models.FileField(_("Аватар"), null=True, blank=True, upload_to=profile_directory_path)
    product_in_history = models.ManyToManyField(to="products.Product", through="UserProductHistory")
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]


class UserProductHistory(models.Model):
    """История посещения пользователем страницы товара"""

    time = models.DateTimeField(auto_now_add=True, verbose_name=_("дата и время посещения"))
    product = models.ForeignKey(to="products.product", on_delete=models.CASCADE)
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name="history_record",
    )

    class Meta:
        ordering = ["-time"]
        verbose_name = _("история посещения")
        verbose_name_plural = _("истории посещения")

market/profiles/forms.py
from django import forms
from django.contrib.auth.forms import BaseUserCreationForm, UsernameField, SetPasswordForm

from django.utils.translation import gettext_lazy as _
from .models import User
from django.core.validators import RegexValidator


class UserRegisterForm(BaseUserCreationForm):
    """
    Форма регистрации пользователя. Запрашивает все необходимые данные.
    Запрашивает у пользователя, хочет ли он стать продавцом на сайте или нет.
    """

    phone = forms.CharField(
        label="Номер телефона",
        max_length=16,
        widget=forms.PasswordInput(
            attrs={"placeholder": "+7(999)999-99-99", "type": "text", "data-mask": "+7(999)999-99-99"}
        ),
        help_text="Вводите номер в виде '+7(ХХХ)ХХХ-ХХ-ХХ'",
        validators=[
            RegexValidator(regex=r"\+[7]\([0-9]{3}\)[0-9]{3}\-[0-9]{2}\-[0-9]{2}", message=_("номер некорректный"))
        ],
    )
    residence = forms.CharField(max_length=80, label="Город проживания")
    address = forms.CharField(
        max_length=80,
        label="Адрес доставки",
        widget=forms.Textarea(attrs={"cols": "60", "rows": "5"}),
    )
    retailer_group = forms.BooleanField(
        initial=False,
        required=False,
        label="Выбрать, если вы хотите стать продавцом на сайте",
    )
    error_messages = {
        "password_mismatch": "Два пароля не совпали.",
    }
    password1 = forms.CharField(
        label="Пароль",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "новый пароль"}),
        help_text="<ul><li>Ваш пароль не должен быть слишком похож на другую "
        "вашу личную информацию.</li>"
        "<li>Ваш пароль должен содержать не менее 8 символов.</li>"
        "<li>Ваш пароль не может быть часто используемым паролем.</li>"
        "<li>Ваш пароль не может быть полностью цифровым.</li></ul>",
    )
    password2 = forms.CharField(
        label="Подтверждение пароля",
        widget=forms.PasswordInput(attrs={"autocomplete": "новый пароль"}),
        strip=False,
        help_text="Введите тот же пароль, что и раньше, для проверки.",
    )

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "phone",
            "residence",
            "address",
            "retailer_group",
        ]

        field_classes = {
            "username": UsernameField,
            "first_name": forms.CharField,
            "last_name": forms.CharField,
            "email": forms.EmailField,
            "phone": forms.CharField,
            "residence": forms.CharField,
            "address": forms.CharField,
            "retailer_group": forms.BooleanField,
            "password1": forms.CharField,
        }


class ChangeProfileInfoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "phone",
            "residence",
            "address",
        ]


class ProfileAvatarUpdateForm(forms.Form):
    user_avatar = forms.ImageField()


class CustomSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
    )

market/profiles/views.py
from django.contrib.auth.models import Group
from django.contrib.auth.views import (
    LogoutView,
    PasswordChangeView,
    LoginView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.contrib.auth import authenticate, login
from django.db import transaction
from django.urls import reverse_lazy, reverse
from django.http.response import HttpResponseRedirect
from django.views.generic import TemplateView, CreateView, UpdateView, ListView
from django.contrib.auth.mixins import UserPassesTestMixin

from .forms import UserRegisterForm, ProfileAvatarUpdateForm, CustomSetPasswordForm
from .models import User
from products.models import Product
from .services.products_history import get_products_in_user_history
from products.services.product_price import product_min_price_or_none
from cart.services.cart_service import login_cart


class AboutUserView(TemplateView):
    """
    View class - информация о пользователе.
    Проверяем авторизован ли пользователь и имеет ли пользователь магазин.
    :context['shop'] (queryset | str): если пользователь имеет магазин,
      то в переменную возвращается queryset магазинов.
      Иначе возвращает пустую строку.
    :context['history'](queryset): если пользователь авторизован,
      то ему показаны последние 3 просмотренных товара.
    """

    template_name = "profiles/about-user.jinja2"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["update_avatar"] = ProfileAvatarUpdateForm()
        user = self.request.user

        if user.is_authenticated:
            history = get_products_in_user_history(user, number=3)
            context["history"] = history
        context["price"] = product_min_price_or_none
        return context

    def post(self, request):
        update_avatar = ProfileAvatarUpdateForm(request.POST, request.FILES)
        if update_avatar.is_valid():
            picture = update_avatar.cleaned_data.get("user_avatar")
            user = User.objects.get(pk=self.request.user.pk)
            user.avatar = picture
            user.save()
            return HttpResponseRedirect(reverse("profiles:about-user"))
        return HttpResponseRedirect(reverse("profiles:about-user"))


class HomePage(TemplateView):
    """View class заглушка - главная страница сайта."""

    template_name = "profiles/index.jinja2"


class UserRegisterView(CreateView):
    """
    View class для регистрации пользователей. Если данные из формы валидны,
    авторизовывает пользователя и перенаправляет на главную страницу сайта.
    """

    form_class = UserRegisterForm
    template_name = "profiles/register.jinja2"
    success_url = reverse_lazy("products:home-page")

    def get(self, request, **kwargs):
        form = UserRegisterForm()
        super().get(form)
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    @transaction.atomic
    def form_valid(self, form):
        response = super().form_valid(form)

        password = form.cleaned_data.get("password1")
        email = form.cleaned_data.get("email")
        retailer_group = form.cleaned_data.get("retailer_group")

        user = authenticate(
            self.request,
            email=email,
            password=password,
        )
        if retailer_group:
            group = Group.objects.get(name="retailer")
            if not user.is_staff:
                user.is_staff = True
            user.groups.add(group)
            user.save()
        login(request=self.request, user=user)
        return response


class UserLogoutView(LogoutView):
    """View class заглушка - user logout."""

    next_page = reverse_lazy("products:home-page")


class UserResetPasswordView(PasswordChangeView):
    """View class смены пароля. Запрашивает у пользователя старый пароль
    и новый пароль дважды.
    Если первый пароль совпадает со вторым, устанавливается новый пароль
    и отправляет пользователя на главную страницу.
    """

    template_name = "profiles/password_form.jinja2"
    success_url = reverse_lazy("products:home-page")


class UserUpdateProfileInfo(UpdateView):
    """View class обновления информации о пользователе."""

    model = User
    template_name = "profiles/user_update_form2.jinja2"
    template_name_suffix = "_update_form"
    success_url = reverse_lazy("profiles:about-user")
    fields = [
        "username",
        "first_name",
        "last_name",
        "email",
        "phone",
        "residence",
        "address",
        "avatar",
    ]


class UserHistoryView(UserPassesTestMixin, ListView):
    template_name = "profiles/product-history.jinja2"
    model = Product
    context_object_name = "history"
    extra_context = {"price": product_min_price_or_none}

    def get_queryset(self):
        user = self.request.user
        return get_products_in_user_history(user)

    def test_func(self):
        return self.request.user.is_authenticated


class CustomLoginView(LoginView):
    def post(self, request, *args, **kwargs):
        answer = super().post(request, *args, **kwargs)
        if self.request.user.is_authenticated:
            login_cart(self.request)
        return answer


class CustomPasswordResetView(PasswordResetView):
    subject_template_name = "profiles/password_reset_subject.txt"
    email_template_name = "profiles/password_reset_email.html"
    success_url = reverse_lazy("profiles:reset_password_done")
    template_name = "profiles/password_reset_form.jinja2"


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = "profiles/password_reset_done.jinja2"


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    success_url = reverse_lazy("profiles:reset_password_complete")
    template_name = "profiles/password_reset_confirm.jinja2"
    form_class = CustomSetPasswordForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_"] = self.user
        return context


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = "profiles/password_reset_complete.jinja2"

market/templates/profiles/about-user.jinja2
{% extends 'profiles/account_base.jinja2' %}

{% block title %}
{{_("Информация о пользователе")}}
{% endblock %}


{% block activate_cabinet %}
{% include "profiles/activate_menu.jinja2" %}
{% endblock %}


{% block account_content %}
<div class="Profile">
    <div class="row-block">
        <h2 class="Section-title">{{_("Страница детальной информации")}}</h2>
        <h3 class="header">{{_("Здравствуйте,")}} {{ user.username }}</h3>
    </div>
</div>
<div class="row">
<!--========================================== AVATAR!  НАЧАЛО  ==========================================-->
    <div class="row-block">
        {% if user.avatar %}
        <div class="form-group">

            <div class="Profile-avatar">
            <p style="display: flex; just"><img src="{{ user.avatar.url }}" alt="{{ user.avatar.name }}" height="268px"></p>
            </div>
             <div class="form-group">
                <label class="form-label" for="avatar-new">{{_("Сменить аватар")}}</label>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="Profile-avatar Profile-avatar_noimg" style="height: 80px;">
                        <label class="Profile-fileLabel" for="avatar-new">
                            <img src="{{ static('assets/img/icons/upload.png') }}" alt="#.png" />
                            {{_("Загрузить фото")}}</label>
                        <input type="file" id="avatar-new" class="Profile-file form-input" accept="image/*" name="user_avatar" data-validate="onlyImgAvatar"></label>
                    </div>
                   <button type="submit" class="btn btn_square btn_dark" style="margin-top:80px">{{_("Обновить аватар")}}</button>
                </form>
            </div>
        </div>
        {% else %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label class="form-label" for="avatar">{{_("Аватар")}}</label>
                <div class="Profile-avatar Profile-avatar_noimg">
                <label class="Profile-fileLabel" for="avatar">
                    <img src="{{ static('assets/img/icons/upload.png') }}" alt="#.png" />
                    {{_("Загрузить фото")}}</label>
                <input type="file" id="avatar" class="Profile-file form-input" accept="image/*" name="user_avatar" data-validate="onlyImgAvatar"></label>
                </div>
            </div>
            <button type="submit" class="btn btn_square btn_dark" style="margin-top:80px">{{_("Обновить аватар")}}</button>
        </form>

        {% endif%}

    </div>
<!--========================================== AVATAR!  КОНЕЦ  ==========================================-->
<!--========================================== Информация пользователя пользователя!  НАЧАЛО  ==========================================-->
    <div class="row-block">
        <h3>{{_("Информация о пользователе")}}</h3>
        <p class="Cart-title">{{_("Никнейм пользователя:")}} {{ user.username }}</p>
        <p class="Cart-title">{{_("Имя:")}} {{ user.first_name }}</p>
        <p class="Cart-title">{{_("Фамилия:")}} {{ user.last_name }}</p>
        <p class="Cart-title">{{_("Email:")}} {{ user.email }}</p>
        <p class="Cart-title">{{_("Телефон:")}} {{ user.phone }}</p>
        <p class="Cart-title">{{_("Город проживания:")}} {{ user.residence }}</p>
        <p class="Cart-title">{{_("Адрес:")}} {{ user.address }}</p>
        <a class="btn btn_square btn_dark" href="{{ url('profiles:update-info', pk=user.pk) }}" style="margin-bottom: 15px;">{{_("Изменить профиль")}}</a>
    </div>
<!--========================================== Информация пользователя пользователя!  КОНЕЦ  ==========================================-->
</div>
<!--========================================== Раздел история просмотра товаров!  НАЧАЛО  ==========================================-->
{% if history %}
<div class="row-block">
        <h2></h2>
        <h3 class="header">{{_("Вы смотрели")}}</h3>
</div>

<div class="Account-group">
   {% for product in history %}
       {% include "profiles/product_card.jinja2" %}
   {% endfor %}
</div>
<a href="{{url('profiles:browsing_history')}}" class="btn btn_square btn_dark" style="margin-bottom: 15px;">{{_("Перейти к полной истории")}}</a>
{% endif %}
<!--========================================== Раздел история просмотра товаров!  КОНЕЦ  ==========================================-->
{% endblock %}

market/templates/profiles/account_base.jinja2
{% extends 'base.jinja2' %}

{% block title %}

{% endblock %}

{% block middle %}
{% if user.is_authenticated %}


<div class="Middle Middle_top">
    <div class="Section Section_column Section_columnLeft">
        <div class="wrap">
<!--========================================== SIDE BAR!  НАЧАЛО   ==========================================-->
            <div class="Section-column">
                <div class="Section-columnSection">
                    <header class="Section-header">
                        <strong class="Section-title">{{_("Навигация")}}
                        </strong>
                    </header>
                    <div class="Section-columnContent">
                        <div class="NavigateProfile">
                            <ul class="menu menu_vt">
                                <li class="{% block activate_cabinet %} menu-item {% endblock %}">
                                    <a class="menu-link" href="{{ url('profiles:about-user') }}">{{_("Личный кабинет")}}</a>
                                </li>
                                <li class="{% block activate_profile %} menu-item {% endblock %}">
                                    <a class="menu-link" href="{{ url('profiles:update-info', pk=user.pk) }}">{{_("Профиль")}}</a>
                                </li>
                                <li class="{% block history_order %} menu-item {% endblock %}">
                                    <a class="menu-link" href="{{ url('orders:history') }}">{{_("История заказов")}}</a>
                                </li>
                                <li class="{% block history_product %} menu-item {% endblock %}">
                                    <a class="menu-link" href="{{ url('profiles:browsing_history') }}">{{_("История просмотра")}}</a>
                                </li>
                                <li class="{% block change_password %} menu-item {% endblock %}">
                                    <a class="menu-link" href="{{ url('profiles:change-password') }}">{{_("Сменить пароль")}}</a>
                                </li>
                                <li class="{% block to_main %} menu-item {% endblock %}">
                                    <a class="menu-link" href="{{ url('products:home-page') }}">{{_("На главную")}}</a>
                                </li>
                                {% if user.shops.count() != 0 %}
                                <h3 class="header">{{_("Информация о магазине")}}</h3>
                                    {% for shop in user.shops.all() %}
                                    <li class="menu-item">
                                        <a class="menu-link" href="{{ url('shops:shop_detail', pk=shop.pk)}}">{{ shop.name }}</a>
                                    </li>
                                    {% endfor %}

                                {% else %}

                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="Section-content">
                {% block account_content %}

                {% endblock %}
            </div>
        </div>
    </div>
</div>
{% else %}
{% trans trimmed url_login = url('profiles:login'), url_register = url('profiles:register') %}
<h2>Вы зашли как анонимный пользователь.</h2>
<p>Пожалуйста,
    <a href="{{ url_login }}">авторизуйтесь</a> или <a href="{{ url_register }}">зарегистрируйтесь.</a>
</p>
{% endtrans %}
{% endif %}
{% endblock %}

market/templates/profiles/activate_menu.jinja2
menu-item_ACTIVE menu-item

market/templates/profiles/login.jinja2
{% extends 'base.jinja2' %}

{% block title -%}
{{_("Login page")}}
{% endblock %}

{% block middle %}

<div class="Middle">
  <div class="Section">
      <div class="wrap">
        <div class="wrapper">
          <h2>{% block name %} {{_("Login page")}} {% endblock %}</h2>
          {% block content %}
          {% if form.errors %}
          <p>{{ form.errors }}</p>
          {% endif %}


          <form method="post">
          {% csrf_token %}
          <p>
<!--            <label for="id_username">Email address:</label>-->
            <input class="user-input" type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="254" required id="id_username" placeholder="E-mail">
          </p>
          <p>
<!--            <label for="id_password">Password:</label>-->
            <input class="user-input" type="password" name="password" autocomplete="current-password" required id="id_password" placeholder="*********">
          </p>
          <input type="submit" value="Login">
          <a class="forgot-label" href="{{url('profiles:reset_password')}}">{{_("Забыли пароль?")}}</a>
          <a class="registr" href="{{ url('profiles:register') }}">{{_("Регистрация")}}</a>
                    <!--    <button type="submit" class="btn btn_square btn_dark">Login</button>-->
          </form>
          {% endblock %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

market/templates/profiles/password_form.jinja2
{% extends 'profiles/account_base.jinja2' %}
{# {% extends 'base.jinja2' %} #}

{% block title %}
{{_("Смена пароля")}}
{% endblock %}


{% block change_password %}
{% include "profiles/activate_menu.jinja2" %}
{% endblock %}


{% block account_content %}
                <div class="Profile">
                    <div class="row-block">
                        <h2 class="Section-title">{{_("Страница смены пароля для пользователя:")}} {{ user.username }}</h2>
                    </div>
                </div>
                <div class="row">
                    <!--================================== Смена пароля начало ==================================-->
                    <div class="row-block">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p() }}
                            <button type="submit" class="btn btn_square btn_dark">{{_("Change password")}}</button>
                        </form>
                    </div>
                    <div class="row-block"></div>
                    <!--================================== Смена пароля конец ===================================-->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

market/templates/profiles/password_reset_complete.jinja2
{% extends 'profiles/login.jinja2' %}

{% block title %}
Megano - {{title}}
{% endblock %}

{% block name %}
{{title}}
{% endblock %}

{% block content %}
<p>Пароль для пользователя успешно изменен</p>
{% endblock %}

market/templates/profiles/password_reset_confirm.jinja2
{% extends 'profiles/login.jinja2' %}

{% block title %}
Megano - {{title}}
{% endblock %}

{% block name %}
{{title}}
{% endblock %}

{% block content %}
  {% if validlink %}
     <h3 class="header">{{_("Пользователь")}} {{ user_.username }}</h3>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p() }}
      <button type="submit">Подтвердить</button>
    </form>
  {% else %}
    <p>
      Вероятно ссылка неверна или уже была использована
    </p>
  {% endif %}
{% endblock %}

market/templates/profiles/password_reset_email.html
{% extends "base.html" %}
{% block middle %}
{% autoescape off %}
Восстановление пароля для пользователя {{ user.get_username }}. Перейдите по следующей ссылке:
{{ protocol }}://{{ domain }}{% url 'profiles:reset_password_confirm' uidb64=uid token=token %}
{% endautoescape %}
{% autoescape on %}
{% endautoescape %}
{% endblock %}

market/templates/profiles/password_reset_form.jinja2
{% extends 'profiles/login.jinja2' %}

{% block title %}
Megano - {{title}}
{% endblock %}

{% block name %}
{{title}}
{% endblock %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p() }}
        <button type="submit">Отправить</button>
    </form>
{% endblock %}

market/templates/profiles/product-history.jinja2
{% extends 'profiles/account_base.jinja2' %}

{% block title %}
{{_("История просмотра пользователя")}}
{% endblock %}


{% block history_product %}
{% include "profiles/activate_menu.jinja2" %}
{% endblock %}

{% block account_content %}
    <div class="Profile">
        <div class="row-block">
            <h2 class="Section-title">{{_("Ваша история просмотра")}}</h2>
        </div>
    </div>
    {% if history %}
    <div class="Cards">
        {% for product in history %}
        {% include "profiles/product_card.jinja2" %}
        {% endfor %}
    </div>
    {% else %}
        <p class="Cart-title">{{_("Тут будет ваша история посещения страницы товаров")}}</p>
    {% endif %}
{% endblock %}

market/templates/profiles/product_card.jinja2
<!--ПЕРЕДАЙ В КОНТЕКСТ ПЕРЕМЕННУЮ product = Product() -->
<div class="Card"><a class="Card-picture" href="{{ product.get_absolute_url() }}">
    <img src="{{ product.preview.url }}" alt="product_preview.jpg" />
</a>
    <div class="Card-content">
        <strong class="Card-title"><a href="{{ product.get_absolute_url() }}">{{ product.name }}</a>
        </strong>
        <div class="Card-description">
            <div class="Card-cost">
                <span class="Card-price">
                    {% if price(product) %}
                    {# Translators: "От" {{price}} #}
                        {{_("От")}} {{ price(product) }} р
                    {% else %}
                        {{_("Нет в наличие")}}
                    {% endif %}
                </span>
            </div>
            <div class="Card-category">
                {% for tag in product.tags.all() %}
                {{ tag.name }}/
                {% endfor %}
            </div>
        </div>
    </div>
</div>

market/templates/profiles/register.jinja2
{% extends 'base.jinja2' %}

{% block title %}
{{_("Registration page")}}
{% endblock %}

{% block extraheader %}

{% endblock %}


{% block middle %}

<div class="Middle">
  <div class="Section">
    <div class="wrap">
      <div class="wrapper" style="width: 600px;">
<!--      <div class="Cards" style="margin-bottom: 0;">-->
        <h2 class="header">{{_("Страница регистрации")}}</h2>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p() }}
          <input type="submit" value="Registration">
<!--          <button type="submit" class="btn btn_square btn_dark">Registration</button>-->
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

market/templates/profiles/user_update_form2.jinja2
{% extends 'profiles/account_base.jinja2' %}

{% block title %}
{{_("Информация о пользователе")}}
{% endblock %}


{% block activate_profile %}
{% include "profiles/activate_menu.jinja2" %}
{% endblock %}


{% if user.is_authenticated %}
    {% block account_content %}
        <div class="Profile">
            <div class="row-block">
                <h2 class="Section-title">{{_("Редактирование профиля")}}</h2>
                <h3 class="header">{{_("Здравствуйте,")}} {{ user.username }}</h3>
            </div>
        </div>
        <div class="row">
<!--============ Изменение информации о пользователе!  НАЧАЛО ============-->
            <div class="row-block">
               <form method="post" enctype="multipart/form-data">
                   {% csrf_token %}
                   {{ form.as_p() }}
               <button type="submit">{{_("Обновить информацию")}}</button>
               </form>

            </div>
            <div class="row-block"></div>
        </div>
    {% endblock %}
<!--============ Изменение информации о пользователе!  КОНЕЦ ============-->
{% endif %}