market/cart/urls.py
from django.urls import path
from .views import (
    CartView,
    AddCartFromProduct,
    RemoveOneCartView,
)

app_name = "cart"

urlpatterns = [
    path("", CartView.as_view(), name="user_cart"),
    path("add", AddCartFromProduct.as_view(), name="add_cart"),
    path("delete", RemoveOneCartView.as_view(), name="delete_cart"),
]

market/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path("settings/", include("site_settings.urls")),
    path("api/", include("api_payments.urls")),
]

urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path("", include("products.urls")),
    path("profiles/", include("profiles.urls")),
    path("shops/", include("shops.urls")),
    path("catalog/", include("catalog.urls")),
    path("cart/", include("cart.urls")),
    path("comparison/", include("comparison.urls")),
    path("pay/", include("payapp.urls")),
    path("orders/", include("orders.urls")),
    path("importdata/", include("importdata.urls")),
    path("discounts/", include("discount.urls")),
)

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS))

market/importdata/urls.py
from django.urls import path

from .views import ImportView


app_name = "importdata"

urlpatterns = [
    path("", ImportView.as_view(), name="importdata"),
]

market/importdata/forms.py
from django import forms
import os
from django.conf import settings

IMPORT_FOLDER_PATH = settings.IMPORT_FOLDER


class ImportForm(forms.Form):
    files = forms.MultipleChoiceField(
        choices=[
            (file, file)
            for file in os.listdir(os.path.abspath(IMPORT_FOLDER_PATH))
            if os.path.isfile(os.path.join(IMPORT_FOLDER_PATH, file))
        ],
        label="Выбирете файл(ы) для импорта. *Если ни один файл не выбран, "
        "импорт будет инициирован из всех указанных файлов:",
        widget=forms.CheckboxSelectMultiple(),
        required=False,
    )

    mail_to = forms.EmailField(
        label="Адрес для отправки отчета:", widget=forms.EmailInput(attrs={"placeholder": "example@gmail.com"})
    )

market/importdata/views.py
import os

from django.contrib.auth.mixins import UserPassesTestMixin
from django.urls import reverse_lazy
from django.core import management
from django.core.cache import cache
from django.conf import settings
from django.views.generic.edit import FormView

from .forms import ImportForm


class ImportView(UserPassesTestMixin, FormView):
    """
    View class для отображения страницы с формой для импорта товаров.
    Если форма валидна - запускается команда импорта товаров.
    """

    form_class = ImportForm
    template_name = "importdata/import.jinja2"
    success_url = reverse_lazy("importdata:importdata")

    def form_valid(self, form):
        responce = super().form_valid(form)
        cd = form.cleaned_data
        management.call_command("importdata", *cd["files"], email=cd["mail_to"])
        return responce

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "import_is_running": cache.get("import_is_running"),
                "import_files": [
                    file
                    for file in os.listdir(os.path.abspath(settings.IMPORT_FOLDER))
                    if os.path.isfile(os.path.join(settings.IMPORT_FOLDER, file))
                ],
            }
        )
        return context

    def test_func(self):
        """
        Проверка доступа к странице импорта товаров.
        Если пользователь авторизирован и у него есть магазин
        или пользователь является суперюзером - доступ открыт,
        иначе -  403 Forbidden.
        """
        return (
            self.request.user.is_authenticated and self.request.user.shops.exists() or self.request.user.is_superuser
        )

market/templates/importdata/import.jinja2
{% extends 'base.jinja2'%}

{% block title %}
    {{ _("Страница импорта данных") }}
{% endblock %}

{% block middle %}
    <div class="Middle">
        <div class="wrap">
            {% include "importdata/import_form.jinja2" %}
        </div>
    </div>
{% endblock %}

market/templates/importdata/import_form.jinja2
<div>
    {% if import_is_running %}
        <div class="Section-title">{{ _("Предыдущий импорт ещё не выполнен. Пожалуйста, дождитесь его окончания.") }} </div>
    {% else %}
        {% if import_files %}
            <form action="" method="post" accept-charset="utf-8">
            <label>{{ _("Выбирете файл(ы) для импорта. *Если ни один файл не выбран, импорт будет инициирован для всех файлов из списка.") }}</label>
                <div id="id_files">

                    {% for file in import_files %}
                        <div>
                            <label for="id_files_{{ file }}">
                                <input id="id_files_{{ file }}" type="checkbox" name="files" value="{{ file }}">
                                {{ file }}
                            </label>
                        </div>
                    {% endfor %}
                </div>
                <p></p>
                <div>
                    <label for="mail_to">{{ _("Адрес для отправки отчета:") }}</label>
                    <input id="mail_to" type="email" name="mail_to" placeholder="example@gmail.com" required>
                </div>
                {% csrf_token %}
                <p><input type="submit" value="{{ _("Импортировать") }}"></p>
            {% else %}
                <div class="Section-title">{{ _("Нет файлов для импорта. Пожалуйста, обратитесь к администратору.") }}</div>
            {% endif %}
       </form>
    {% endif %}
</div>