market/cart/urls.py
from django.urls import path
from .views import (
    CartView,
    AddCartFromProduct,
    RemoveOneCartView,
)

app_name = "cart"

urlpatterns = [
    path("", CartView.as_view(), name="user_cart"),
    path("add", AddCartFromProduct.as_view(), name="add_cart"),
    path("delete", RemoveOneCartView.as_view(), name="delete_cart"),
]

market/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path("settings/", include("site_settings.urls")),
    path("api/", include("api_payments.urls")),
]

urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path("", include("products.urls")),
    path("profiles/", include("profiles.urls")),
    path("shops/", include("shops.urls")),
    path("catalog/", include("catalog.urls")),
    path("cart/", include("cart.urls")),
    path("comparison/", include("comparison.urls")),
    path("pay/", include("payapp.urls")),
    path("orders/", include("orders.urls")),
    path("importdata/", include("importdata.urls")),
    path("discounts/", include("discount.urls")),
)

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS))

market/orders/urls.py
from django.urls import path

from orders.views import (
    OrderDetailView,
    OrderStepOneView,
    OrderStepTwoView,
    OrderStepThreeView,
    OrderHistoryListView,
    OrderStepFourView,
)

app_name = "orders"


urlpatterns = [
    path("step_one/", OrderStepOneView.as_view(), name="view_step_one"),
    path("step_two/", OrderStepTwoView.as_view(), name="view_step_two"),
    path("step_three/", OrderStepThreeView.as_view(), name="view_step_three"),
    path("step_four/", OrderStepFourView.as_view(), name="view_step_four"),
    path("history/", OrderHistoryListView.as_view(), name="history"),
    path("detail/<int:pk>/", OrderDetailView.as_view(), name="detail_order"),
]

market/orders/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from profiles.models import User
from django.db.models import Q


class DeliveryType(models.TextChoices):
    """Модель выбора способа доставки."""

    USUALLY = "usually", _("обычная доставка")
    EXPRESS = "express", _("экспресс доставка")


class PaymentType(models.TextChoices):
    """Модель выбора способа оплаты."""

    CARD = "card", _("онлайн картой")
    RANDOM = "random", _("Онлайн со случайного чужого счета")


class Order(models.Model):
    """Класс модели таблицы заказов"""

    STATUS_CREATED = _("создан")
    STATUS_OK = _("выполнен")
    STATUS_DELIVERED = _("доставляется")
    STATUS_PAID = _("оплачен")
    STATUS_NOT_PAID = _("не оплачен")

    STATUS_CHOICES = [
        (
            "Success",
            (
                (STATUS_CREATED, "создан"),
                (STATUS_OK, "выполнен"),
                (STATUS_DELIVERED, "доставляется"),
                (STATUS_PAID, "оплачен"),
            ),
        ),
        (STATUS_NOT_PAID, "не оплачен"),
    ]

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_("дата создания заказа"),
    )
    city = models.CharField(
        max_length=50,
        verbose_name=_("Город доставки"),
        blank=True,
    )
    address = models.CharField(max_length=260, verbose_name=_("адрес доставки"))
    user = models.ForeignKey(User, on_delete=models.CASCADE, db_index=True)
    delivery_type = models.CharField(
        max_length=50,
        choices=DeliveryType.choices,
        default=DeliveryType.USUALLY,
        verbose_name=_("метод доставки"),
    )
    payment_type = models.CharField(
        max_length=50,
        choices=PaymentType.choices,
        # blank=False,
        default=PaymentType.CARD,
        verbose_name=_("способ оплаты"),
    )
    order_number = models.PositiveIntegerField(default=1, verbose_name=_("номер заказа"))
    # fmt: off
    status = models.CharField(
        max_length=15,
        choices=STATUS_CHOICES,
        default=STATUS_CREATED,
        verbose_name="status"
    )
    # fmt: on
    total_price = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        verbose_name=_("общая стоимость"),
    )
    discount_amount = models.DecimalField(
        max_digits=12, decimal_places=2, verbose_name=_("Размер скидки"), default=0.00
    )

    class Meta:
        ordering = ["-created_at"]
        verbose_name = _("заказ")
        verbose_name_plural = _("заказы")
        constraints = [models.CheckConstraint(check=Q(total_price__gte=1.00), name="total_price_lte_1.00")]

    def __str__(self):
        return f"Заказ#{self.pk}:{self.user.username}"

    def get_order_number(self, user: User):
        all_examples = self.objects.filter(user=user).first().order_number
        self.order_number = all_examples + 1
        return self.order_number


class OrderDetail(models.Model):
    """
    Класс модели деталей заказа
    (предложения и продукты загружаемые из корзины)
    """

    offer = models.ForeignKey(
        to="shops.Offer",
        on_delete=models.CASCADE,
        verbose_name=_("Предложение"),
        help_text=_("Выбрать желаемый товар по специальной цене от магазина"),
    )
    quantity = models.PositiveIntegerField(default=1, verbose_name=_("Количество товара"))
    user_order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name="details", verbose_name=_("Номер заказа пользователя")
    )

    class Meta:
        verbose_name = _("заказ пользователя")
        verbose_name_plural = _("заказы пользователя")

    def __str__(self):
        return f"Товар {self.offer.product.name}"

    def get_coast(self):
        return self.offer.price * self.quantity

market/orders/forms.py
from django import forms
from django.forms import TextInput, Textarea, RadioSelect
from orders.models import Order
from profiles.forms import UserRegisterForm
from profiles.models import User


class OrderStepTwoForm(forms.ModelForm):
    """Форма для обработки второго шага заказа товара"""

    class Meta:
        model = Order
        fields = (
            "delivery_type",
            "city",
            "address",
        )
        widgets = {
            "city": TextInput(attrs={"class": "form-input"}),
            "address": Textarea(attrs={"class": "form-textarea"}),
            "delivery_type": RadioSelect,
        }


class OrderStepThreeForm(forms.ModelForm):
    """Форма для обработки третьего шага заказа товара"""

    class Meta:
        model = Order
        fields = ("payment_type",)
        widgets = {
            "payment_type": RadioSelect,
        }


class OrderFastRegistrationAnonymousUser(UserRegisterForm):
    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "phone",
        ]


class OrderStepFourForm(forms.ModelForm):
    """
    Форма для обработки четвертого шага заказа товара.
    """

    class Meta:
        model = Order
        fields = (
            "delivery_type",
            "city",
            "address",
            "payment_type",
        )

market/orders/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, FormView
from orders.forms import OrderStepTwoForm, OrderStepThreeForm, OrderFastRegistrationAnonymousUser

from orders.models import Order, OrderDetail
from orders.services.services import OrderDetailCreate
from profiles.models import User
from profiles.views import UserRegisterView


class OrderDetailView(PermissionRequiredMixin, DetailView):
    """
    Страница отображения деталей заказа при переходе на заказ из истории заказов.
    """

    model = Order
    template_name = "orders/detail_order.jinja2"

    def has_permission(self):
        return self.get_object().user == self.request.user or self.request.user.is_superuser


class OrderStepOneView(LoginRequiredMixin, UserRegisterView):
    """
    Отображение первого шага заказа.
    Если пользователь зарегистрирован перенаправляет его сразу на следующий шаг.
    """

    template_name = "orders/order_step_one.jinja2"
    success_url = reverse_lazy("order:order_step_2")
    form_class = OrderFastRegistrationAnonymousUser

    def get(self, request, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse("orders:view_step_two"))

        form = OrderFastRegistrationAnonymousUser()
        super().get(form)
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def form_valid(self, form):
        response = super().form_valid(form)
        return response


class OrderStepTwoView(FormView):
    """Отображает страницу второго шага заказа"""

    form_class = OrderStepTwoForm
    template_name = "orders/order_step_two.jinja2"

    def form_valid(self, form):
        self.request.session["delivery_type"] = form.cleaned_data.get("delivery_type")
        self.request.session["city"] = form.cleaned_data.get("city")
        self.request.session["address"] = form.cleaned_data.get("address")
        return super().form_valid(form)

    def get_initial(self):
        initial = super().get_initial()
        if self.request.session.get("delivery_type"):
            initial["delivery_type"] = self.request.session.get("delivery_type")

        if self.request.session.get("city"):
            initial["city"] = self.request.session.get("city")

        if self.request.session.get("address"):
            initial["address"] = self.request.session.get("address")

        return initial

    def get_success_url(self):
        return reverse("orders:view_step_three")


class OrderStepThreeView(LoginRequiredMixin, FormView):
    """Отображает страницу третьего шага заказа"""

    form_class = OrderStepThreeForm
    template_name = "orders/order_step_three.jinja2"

    def form_valid(self, form):
        self.request.session["payment_type"] = form.cleaned_data["payment_type"]
        return super().form_valid(form)

    def get_initial(self):
        initial = super().get_initial()
        if self.request.session.get("payment_type"):
            initial["payment_type"] = self.request.session.get("payment_type")
        return initial

    def get_success_url(self):
        OrderDetailCreate(self.request).created_order_details_product()

        self.request.session["cart"] = None
        self.request.session["cart_size"] = None
        self.request.session["cart_price"] = None
        return reverse("orders:view_step_four")


class OrderStepFourView(ListView):
    """View - class для отображения четвёртого шага заказа."""

    model = OrderDetail
    template_name = "orders/order_step_four.jinja2"
    context_object_name = "products"

    def get_queryset(self):
        order = (
            Order.objects.prefetch_related("details")
            .select_related("user")
            .filter(user__pk=self.request.user.pk)
            .first()
        )
        queryset = order.details.all()
        return queryset


class OrderHistoryListView(ListView):
    """View - class для отображения истории заказов пользователя."""

    model = Order
    template_name = "orders/order_history.jinja2"
    context_object_name = "orders"

    def get_queryset(self):
        user = User.objects.get(pk=self.request.user.pk)
        queryset = (
            Order.objects.filter(user=user)
            .select_related("user")
            .prefetch_related(
                "details",
            )
        )
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["history"] = self.get_queryset()
        return context

market/templates/orders/detail_order.jinja2
{% extends 'base.jinja2' %}


{% block title %}
Детальная информация заказа {{ order.pk }}
{% endblock %}


{% block middle %}
<div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">Заказ №{{ order.order_number }}
                </h1>
            </div>
        </div>
    </div>

    <div class="Section">
        <div class="wrap">
            <div class="Section-content">
                <div class="Orders">
                </div>

<!--========== ЗАКАЗ ==========                 -->
    <div class="Order">
        <div class="Order-infoBlock">
            <div class="Order-personal">
                <div class="row">
                    <div class="row-block">
                    <div class="Order-info Order-info_date">
                        <div class="Order-infoType">Дата заказа:
                        </div>
                        <div class="Order-infoContent">{{ order.created_at.date()}}
                        </div>
                    </div>
                    <div class="Order-info">
                        <div class="Order-infoType">ФИО:
                        </div>
                        <div class="Order-infoContent">{{ order.user.first_name }} {{ order.user.last_name }}
                        </div>
                    </div>
                    <div class="Order-info">
                        <div class="Order-infoType">Телефон:
                        </div>
                        <div class="Order-infoContent"> {{ order.user.phone }}
                        </div>
                    </div>
                    <div class="Order-info">
                        <div class="Order-infoType">E-mail:
                        </div>
                        <div class="Order-infoContent">{{ order.user.email }}
                        </div>
                    </div>
                </div>
                <div class="row-block">
                    <div class="Order-info Order-info_delivery">
                        <div class="Order-infoType">Тип доставки:
                        </div>
                        <div class="Order-infoContent">{{ order.get_delivery_type_display() }} {# {{ order.DELIVERY_TYPE_DICT[order.delivery_type] }} #}
                        </div>
                    </div>
                    <div class="Order-info">
                        <div class="Order-infoType">Город:
                        </div>
                        <div class="Order-infoContent">{{ order.city }}
                        </div>
                    </div>
                    <div class="Order-info">
                        <div class="Order-infoType">Адрес:
                        </div>
                        <div class="Order-infoContent">{{ order.address }}
                        </div>
                    </div>
                    <div class="Order-info Order-info_pay">
                        <div class="Order-infoType">Оплата:
                        </div>
                        <div class="Order-infoContent">{{ order.get_payment_type_display().title() }} {# {{ order.PAYMENT_TYPES_DICT[order.payment_type].title() }} #}
                        </div>
                    </div>
                    <div class="Order-info Order-info_status">
                        <div class="Order-infoType">Статус:
                        </div>
                        <div class="Order-infoContent">{{ order.status }}
                        </div>
                    </div>
                    {% if order.status.lower() == "не оплачен" or order.status == "создан" %}

        <!--===================== если оплата не прошла ==============================-->
                    <div class="Order-info Order-info_error">
                        <div class="Order-infoType">Оплата не прошла:
                        </div>
                        <div class="Order-infoContent">Оплата не выполнена
                        </div>
                    </div>
        <!--===================== если оплата не прошла ==============================-->
                    {% endif %}
                    </div>
                </div>
            </div>
<!-- ========== ЗАКАЗ ========== -->


<!-- ========== Товары в заказе ========== -->
                        <div class="Cart Cart_order">
                            <div class="Cart-product">
                                <div class="Cart Cart_order">
                                    {% for product in order.details.all() %}
                                    <div class="Cart-product">
                                        <div class="Cart-block Cart-block_row">
                                            <div class="Cart-block Cart-block_pict">
                                                <a class="Cart-pict" href="{{ url('products:product-detail', pk=product.offer.product.pk) }}">
                                                    {% set product_name=product.offer.product.name %}
                                                    <img class="Cart-img" src="{{ product.offer.product.preview.url }}" alt="{{ product_name }}" />
                                                </a>
                                            </div>

                                            <div class="Cart-block Cart-block_info">
                                                <a class="Cart-title" href="{{ url('products:product-detail', pk=product.offer.product.pk) }}">{{ product_name }}</a>
                                                <div class="Cart-desc">{{ product.offer.product.description[:120] }}</div>
                                            </div>

                                            <div class="Cart-block Cart-block_price">
                                                <div class="Cart-price">{{ product.offer.price }}</div>
                                                <div class="Cart-desc">за 1 ед.</div>
                                            </div>

                                        </div>
                                        <div class="Cart-block Cart-block_row">
                                            <div class="Cart-block Cart-block_amount">{{ product.quantity }} шт.
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>

                            </div>
                            <div class="Cart-total">
                                <div class="Cart-block Cart-block_total">
                                    <strong class="Cart-title">Скидка:<span class="Cart-price">{{ order.discount_amount }}</span>
                                    </strong>
                                </div>
                                <div class="Cart-block Cart-block_total">
                                    <strong class="Cart-title">Итого:<span class="Cart-price">{{ order.total_price }}</span>
                                    </strong>
                                </div>
                                {% if order.status == STATUS_NOT_PAID or STATUS_CREATED %}
                                <div class="Cart-block"><a class="btn btn_primary btn_lg" href="#">Оплатить</a>
                                </div>
                                {% endif %}


                            </div>
                            {% if order.status.lower() == "не оплачен" or order.status == "создан" %}

                            <div class="Cart-block">
                                <a class="btn btn_primary btn_lg" href="{{ url('payapp:order_pay', order.pk) }}">Оплатить</a>
                            </div>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ========== Товары в заказе ========== -->

{% endblock %}

market/templates/orders/order_base.jinja2
{% extends 'base.jinja2' %}

{% block title %}

{% endblock %}


{% block middle %}

<div class="Middle Middle_top">
    <div class="Section Section_column Section_columnRight Section_columnWide Order">
        <div class="wrap">
            <div class="Section-column">
                {% block sidebar %}
                <div class="Section-columnSection">
                    <header class="Section-header">
                        <strong class="Section-title">
                            {{_("Прогресс заполнения")}}
                        </strong>
                    </header>
                    <div class="Section-columnContent">
                        <div class="NavigateProfile">
                            <ul class="menu menu_vt">
                                <li class="{% block step_one %} menu-item {% endblock %}"><a class="menu-link" href="#step1">
                                    {{_("Шаг 1. Параметры пользователя")}}</a>
                                </li>
                                <li class="{% block step_two %} menu-item {% endblock %}"><a class="menu-link" href="#step2">
                                    {{_("Шаг 2. Способ доставки")}}</a>
                                </li>
                                <li class="{% block step_three %} menu-item {% endblock %}"><a class="menu-link" href="#step3">
                                    {{_("Шаг 3. Способ оплаты")}}</a>
                                </li>
                                <li class="{% block step_four %} menu-item {% endblock %}"><a class="menu-link" href="#step4">
                                    {{_("Шаг 4. Подтверждение заказа")}}</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                {% endblock %}
            </div>
            <div class="Section-content">
                {% block order_content %}

                {% endblock %}
            </div>
        </div>

    </div>
</div>
{% endblock %}

market/templates/orders/order_history.jinja2
{% extends 'profiles/account_base.jinja2' %}

{% block title %}
История просмотра пользователя
{% endblock %}


{% block history_order %}
{% include "profiles/activate_menu.jinja2" %}
{% endblock %}

{% block account_content %}
<div class="Orders">
<!--============================================= начало заказа =============================================-->
    {% for order in orders %}
    <div class="Order Order_anons">
        <div class="Order-personal">
            <div class="row">
                <div class="row-block">
                    <a class="Order-title" href="{{ url('orders:detail_order', pk=order.pk) }}">Заказ&#32;
                        <span class="Order-numberOrder">№{{ order.order_number }}</span>
                        &#32;от&#32;
                        <span class="Order-dateOrder">{{ order.created_at.date() }}</span>
                    </a>
                </div>
                <div class="row-block">
                    <div class="Order-info Order-info_delivery">
                        <div class="Order-infoType">Тип доставки:
                        </div>
                        <div class="Order-infoContent"> {{ order.get_delivery_type_display() }} {# {{ order.DELIVERY_TYPE_DICT[order.delivery_type].title() }} #}
                        </div>
                    </div>
                    <div class="Order-info Order-info_pay">
                        <div class="Order-infoType">Оплата:
                        </div>
                        <div class="Order-infoContent">{{ order.get_payment_type_display() }} {# {{ order.PAYMENT_TYPES_DICT[order.payment_type].title() }} #}
                        </div>
                    </div>
                    <div class="Order-info">
                        <div class="Order-infoType">Общая стоимость:
                        </div>
                        <div class="Order-infoContent"><span class="Order-price"><b>{{ order.total_price }} &#x20bd;</span>
                        </div>
                    </div>
                    <div class="Order-info Order-info_status">
                        <div class="Order-infoType">Статус:
                        </div>
                        <div class="Order-infoContent"> {{ order.status.title() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% else %}
        <h2>У вас еще нет заказов</h2>
    {% endfor %}
<!--============================================= конец заказа =============================================-->
</div>


{% endblock %}

market/templates/orders/order_step_four.jinja2
{% extends 'orders/order_base.jinja2' %}


{% block title %}
{{_('Заказ товара. Шаг 4')}}
{% endblock %}


{% block step_four %}
{% include "profiles/activate_menu.jinja2" %}
{% endblock %}


{% block order_content %}
<!--мы на четвёртой странице-->
{# {{ user=products.first().user_order.user }} #}
{% set order_info=products.first().user_order %}
<form class="form" action="{{url('payapp:order_pay', order_info.pk)}}" method="get">
    <div class="Order-block Order-block_OPEN" id="step1">
        <header class="Section-header Section-header_sm">
            <h2 class="Section-title">{{_('Шаг 4. Подтверждение заказа')}}

            </h2>
        </header>
        <div class="Order-infoBlock">


            <div class="Order-personal">

                <div class="row">
                    <div class="row-block">
                        <div class="Order-info">
                            <div class="Order-infoType">{{_('ФИО:')}}
                            </div>
<!-- ============================username ================================-->

                            <div class="Order-infoContent">{{ user.first_name }} {{ user.last_name }}
                            </div>
                        </div>
<!-- ============================ телефон ================================-->
                        <div class="Order-info">
                            <div class="Order-infoType">{{_('Телефон:')}}
                            </div>
                            <div class="Order-infoContent">{{ user.phone }}
                            </div>
                        </div>
<!-- ============================ email ================================-->
                        <div class="Order-info">
                            <div class="Order-infoType">{{_('E-mail:')}}
                            </div>
                            <div class="Order-infoContent">{{ user.email }}
                            </div>
                        </div>
                    </div>
                    <div class="row-block">
                        <div class="Order-info Order-info_delivery">
                            <div class="Order-infoType">{{_('Тип доставки:')}}
                            </div>
<!--============================ тип доставки ================================-->
                            <div class="Order-infoContent">{{ order_info.get_delivery_type_display() }} {# {{ order_info.DELIVERY_TYPE_DICT[order_info.delivery_type].title() }} #}
                            </div>
                        </div>
                        <div class="Order-info">
                            <div class="Order-infoType">{{_('Город:')}}
                            </div>
                            <div class="Order-infoContent"> {{ order_info.city }}
                            </div>
                        </div>
                        <div class="Order-info">
                            <div class="Order-infoType">{{_('Адрес:')}}
                            </div>
                            <div class="Order-infoContent">{{ order_info.address }}
                            </div>
                        </div>
                        <div class="Order-info Order-info_pay">
                            <div class="Order-infoType">{{_('Оплата:')}}
                            </div>
                            <div class="Order-infoContent"> {{ order_info.get_payment_type_display() }}{# {{ order_info.PAYMENT_TYPES_DICT[order_info.payment_type].title() }} #}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
<!--=================== Список товаров ==============================-->

            <div class="Cart Cart_order">
                {% for prod in products %}
<!--=================== Карта товара  ==============================-->
                <div class="Cart-product">
                    <div class="Cart-block Cart-block_row">
                        <div class="Cart-block Cart-block_pict">
                            <a class="Cart-pict" href="{{ url( 'products:product-detail', pk=prod.offer.product.pk)}}">
                                <img class="Cart-img" src="{{ prod.offer.product.preview.url }}" alt="{{ prod.offer.product.name}}" />
                            </a>
                        </div>
                        <div class="Cart-block Cart-block_info"><a class="Cart-title" href="#">{{ prod.offer.product.name }}</a>
                            <div class="Cart-desc">{{ prod.offer.product.description[:80] }} ...
                            </div>
                        </div>
                        <div class="Cart-block Cart-block_price">
                            <div class="Cart-price">{{ prod.offer.price }}&#160;р
                            </div>
                            <div class="Cart-block">{{_("за 1 ед.") }}
                            </div>
                        </div>
                    </div>
                    <div class="Cart-block Cart-block_row">
                        <div class="Cart-block Cart-block_amount"> {{ prod.quantity }} шт.
                        </div>
                    </div>
                </div>
                {% endfor %}
<!--=================== Карта товара  ==============================-->



<!--=================== Итоговая цена товаров ==============================-->
                <div class="Cart-total">
                    <div class="Cart-block Cart-block_total">
                        <strong class="Cart-title">{{_('Скидка:')}}
                        </strong><span class="Cart-price"> {{ order_info.discount_amount }} р</span>
                    </div>
                    <div class="Cart-block Cart-block_total">
                        <strong class="Cart-title">{{_('Итого:')}}
                        </strong><span class="Cart-price"> {{ order_info.total_price }} р</span>
                    </div>
                    <div class="Cart-block">
                        <button class="btn btn_primary btn_lg" type="submit">{{_('Оплатить')}}
                        </button>
                    </div>
                </div>
            </div>

<!--=================== Итоговая цена товаров ==============================-->
<!--=================== Список товаров ==============================-->
        </div>
    </div>
</form>

{% endblock %}