market/cart/urls.py
from django.urls import path
from .views import (
    CartView,
    AddCartFromProduct,
    RemoveOneCartView,
)

app_name = "cart"

urlpatterns = [
    path("", CartView.as_view(), name="user_cart"),
    path("add", AddCartFromProduct.as_view(), name="add_cart"),
    path("delete", RemoveOneCartView.as_view(), name="delete_cart"),
]

market/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path("settings/", include("site_settings.urls")),
    path("api/", include("api_payments.urls")),
]

urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path("", include("products.urls")),
    path("profiles/", include("profiles.urls")),
    path("shops/", include("shops.urls")),
    path("catalog/", include("catalog.urls")),
    path("cart/", include("cart.urls")),
    path("comparison/", include("comparison.urls")),
    path("pay/", include("payapp.urls")),
    path("orders/", include("orders.urls")),
    path("importdata/", include("importdata.urls")),
    path("discounts/", include("discount.urls")),
)

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS))

market/products/urls.py
from django.urls import path

from .views import HomeView, ProductView

app_name = "products"

urlpatterns = [
    path("", HomeView.as_view(), name="home-page"),
    path("product/<int:pk>/", ProductView.as_view(), name="product-detail"),
]

market/products/models.py
import os
from typing import Union

from django.db import models
from django.db.models.constraints import UniqueConstraint
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.core.validators import FileExtensionValidator
from django.urls import reverse


def product_images_directory_path(instance: Union["Product", "ProductImage"], filename: str) -> str:
    """Функция получения пути для изображений продукта и превью продукта"""
    if isinstance(instance, ProductImage):
        return "img/products/{name}/{filename}".format(name=instance.product.name, filename=filename)
    return "img/products/{name}/preview_{filename}".format(name=instance.name, filename=filename)


class ProductImage(models.Model):
    """Изображение для продукта"""

    product = models.ForeignKey(
        null=False,
        on_delete=models.CASCADE,
        to="Product",
        verbose_name="продукт",
        related_name="images",
    )
    image = models.ImageField(null=True, blank=True, upload_to=product_images_directory_path)

    class Meta:
        verbose_name = _("изображение")
        verbose_name_plural = _("изображения")

    def delete(self, using=None, keep_parents=False):
        """Удаление файла изображения при удалении экземпляра модели"""
        try:
            os.remove(f"{settings.MEDIA_ROOT}/{self.image}")
        except FileNotFoundError:
            pass
        finally:
            return super().delete(using, keep_parents)


class Product(models.Model):
    """Продукт"""

    class Meta:
        verbose_name = _("продукт")
        verbose_name_plural = _("продукты")

    name = models.CharField(max_length=512, unique=True, verbose_name=_("наименование"))
    manufacturer = models.ForeignKey("Manufacturer", on_delete=models.CASCADE, verbose_name=_("производитель"))
    details = models.ManyToManyField("Detail", through="ProductDetail", verbose_name=_("характеристики"))
    about = models.TextField(blank=True, max_length=512, verbose_name="краткое описание")
    description = models.TextField(blank=True, max_length=1024, verbose_name="описание")
    category = models.ForeignKey(on_delete=models.PROTECT, to="products.category", verbose_name="категория товаров")
    preview = models.ImageField(null=True, blank=True, upload_to=product_images_directory_path)
    tags = models.ManyToManyField(to="Tag", verbose_name=_("теги"), related_name="products", blank=True)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        """Попутное создание экземпляра ProductImage от preview"""
        super().save(force_insert, force_update, using, update_fields)
        if self.preview:
            ProductImage.objects.get_or_create(product=self, image=self.preview)

    def get_absolute_url(self):
        """Method returns a string that can be used to refer to the object over HTTP"""
        return reverse("products:product-detail", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return f"Товар(pk={self.pk}, name={self.name!r})"


class Tag(models.Model):
    """Модель Тег"""

    name = models.CharField(max_length=64, verbose_name=_("название тега"))

    def __str__(self) -> str:
        return f"Тег (pk={self.pk}, name={self.name!r})"


class Detail(models.Model):
    """Свойство продукта"""

    name = models.CharField(max_length=512, verbose_name=_("наименование"))

    class Meta:
        verbose_name = _("свойство продуктов")
        verbose_name_plural = _("свойства продуктов")

    def __str__(self) -> str:
        return f"Детали продукта (pk={self.pk}, name={self.name!r})"


class ProductDetail(models.Model):
    """Значение свойства продукта"""

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    detail = models.ForeignKey(Detail, on_delete=models.CASCADE, related_name="product_value")
    value = models.CharField(max_length=128, verbose_name=_("значение"))

    class Meta:
        verbose_name = _("значение свойства продуктов")
        verbose_name_plural = _("значения свойства продуктов")
        constraints = [UniqueConstraint(fields=["product", "detail"], name="unique_product_detail")]


def category_icon_directory_path(instance: "Category", filename: str) -> str:
    """Функция получения пути для иконок категорий"""
    return "img/icons/categories/{slug}/{filename}".format(
        slug=instance.slug,
        filename=filename,
    )


class Category(models.Model):
    """Категория продукта"""

    name = models.CharField(max_length=128, unique=True, verbose_name=_("наименование"))
    slug = models.SlugField(max_length=128, unique=True, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("дата создания"))
    modified_at = models.DateTimeField(auto_now=True, verbose_name=_("дата последнего изменения"))
    archived = models.BooleanField(default=False, verbose_name=_("архивировано"))
    is_active = models.BooleanField(default=True, verbose_name=_("активно"))
    parent = models.ForeignKey("self", blank=True, null=True, verbose_name=_("родитель"), on_delete=models.CASCADE)
    foreground = models.BooleanField(default=False, verbose_name=_("приоритетный"))
    icon = models.FileField(
        null=True,
        blank=True,
        upload_to=category_icon_directory_path,
        verbose_name=_("иконка"),
        validators=[FileExtensionValidator(["svg", "img", "png"])],
    )

    class Meta:
        verbose_name = _("категория")
        verbose_name_plural = _("категории")
        app_label = "products"
        constraints = [UniqueConstraint(fields=["name", "parent"], name="unique_parent_name")]

    def get_absolute_url(self):
        """Method returns a string that can be used to refer to the object over HTTP"""
        return reverse("catalog:index") + f"?category_id={self.pk}"

    def get_icon_name(self) -> str:
        """
        Получение названия файла иконки
        :return: название файла
        """
        return os.path.basename(self.icon.name)

    def __str__(self) -> str:
        return f"Категория (pk={self.pk}, name={self.name!r})"


class Review(models.Model):
    """Отзыв на продукт"""

    class Meta:
        verbose_name = _("отзыв")
        verbose_name_plural = _("отзывы")
        app_label = "products"

    user = models.ForeignKey("profiles.User", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    review_content = models.TextField(verbose_name=_("отзыв"))
    is_published = models.BooleanField(default=False, verbose_name=_("опубликовано"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("дата создания"))
    modified_at = models.DateTimeField(auto_now=True, verbose_name=_("дата последнего изменения"))
    archived = models.BooleanField(default=False, verbose_name=_("архивировано"))

    def __str__(self) -> str:
        return f"Отзыв (pk={self.pk}, product_id={self.product.id})"


class Manufacturer(models.Model):
    class Meta:
        verbose_name = _("производитель")
        verbose_name_plural = _("производители")

    name = models.CharField(max_length=128, unique=True, verbose_name=_("производитель"))
    slug = models.SlugField(max_length=128, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("дата создания"))
    modified_at = models.DateTimeField(auto_now=True, verbose_name=_("дата последнего изменения"))
    archived = models.BooleanField(default=False, verbose_name=_("архивировано"))

    def __str__(self) -> str:
        return f"Производитель(pk={self.pk}, name={self.name!r})"


def banner_directory_path(instance: "Banner", filename: str) -> str:
    return "img/banner/{filename}".format(
        filename=filename,
    )


class Banner(models.Model):
    """Баннер"""

    class Meta:
        verbose_name = _("баннер")
        verbose_name_plural = _("баннеры")

        constraints = [
            models.CheckConstraint(  # type: ignore
                check=models.Q(category__isnull=False, product__isnull=True, offer__isnull=True)
                | models.Q(category__isnull=True, product__isnull=False, offer__isnull=True)
                | models.Q(category__isnull=True, product__isnull=True, offer__isnull=False),
                name="category_or_product_or_offer",
                violation_error_message="Должно быть заполнено только одно поле.",
            ),
        ]

    name = models.CharField(max_length=512, verbose_name=_("наименование"))
    description = models.TextField(blank=True, max_length=512, verbose_name=_("описание"))
    image = models.ImageField(null=True, blank=True, upload_to=banner_directory_path)
    archived = models.BooleanField(default=False, verbose_name=_("архивировано"))
    category = models.ForeignKey(
        null=True, blank=True, on_delete=models.PROTECT, to="products.category", verbose_name="категория товаров"
    )
    product = models.ForeignKey(
        null=True, blank=True, on_delete=models.PROTECT, to="products.product", verbose_name="товар"
    )
    offer = models.ForeignKey(
        null=True, blank=True, on_delete=models.PROTECT, to="shops.offer", verbose_name="предложение магазина"
    )

    def __str__(self) -> str:
        return f"Баннер (pk={self.pk}, name={self.name!r})"

    def delete(self, using=None, keep_parents=False):
        """Удаление файла изображения при удалении экземпляра модели"""
        path = f"{settings.MEDIA_ROOT}/{self.image}"
        if os.path.isfile(path):
            os.remove(path)


class LimitedOffer(models.Model):
    """Ограниченные предложения"""

    class Meta:
        verbose_name = _("ограниченное предложение")
        verbose_name_plural = _("ограниченные предложения")

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    end_date = models.DateTimeField(null=False, verbose_name=_("дата окончания"))
    archived = models.BooleanField(default=False, verbose_name=_("архивировано"))

market/shops/models.py
from django.core.validators import MinValueValidator
from decimal import Decimal
from django.db import models
from django.utils.translation import gettext_lazy as _

from profiles.models import User


def shop_avatar_path(instance: "User", filename):
    return "shops/{pk}/avatar/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class Shop(models.Model):
    """Магазин"""

    # Магазин связан с пользователем
    user = models.ForeignKey(User, on_delete=models.CASCADE, db_index=True, related_name="shops")
    name = models.CharField(max_length=512, verbose_name=_("название"))
    about = models.TextField(
        verbose_name=_("Описание магазина"),
        help_text=_("Введите краткое описание магазина."),
        default=_("Описание магазина"),
    )
    phone = models.CharField(
        max_length=11,
        verbose_name=_("Телефон магазина"),
        help_text=_("Контактный телефон магазина."),
        default="89001112233",
    )
    email = models.EmailField(
        verbose_name=_("Емаил магазина"),
        help_text=_("Контактный емаил магазина."),
        null=True,
    )
    avatar = models.ImageField(verbose_name=_("Аватар"), upload_to=shop_avatar_path, null=True)
    products = models.ManyToManyField(
        "products.Product",
        through="Offer",
        related_name="shops",
        related_query_name="shop",
        verbose_name=_("товары в магазине"),
    )

    class Meta:
        verbose_name = _("магазин")
        verbose_name_plural = _("магазины")

    def __str__(self) -> str:
        return f"Продавец (pk={self.pk}, name={self.name!r})"


class PaymentMethod(models.TextChoices):
    """Модель для выбора способа оплаты"""

    CARD = "CARD", _("Банковской картой")
    CASH = "CASH", _("Наличными")


class DeliveryMethod(models.TextChoices):
    """Модель для выбора способа доставки"""

    FREE = "FREE", _("Бесплатная доставка")
    REGULAR = "REGULAR", _("Обычная доставка")
    EXPRESS = "EXPRESS", _("Экспресс доставка")


class Offer(models.Model):
    """Предложение магазина"""

    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    product = models.ForeignKey("products.Product", on_delete=models.CASCADE, related_name="offers")
    price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name=_("цена"), validators=[MinValueValidator(Decimal("0.01"))]
    )
    remains = models.PositiveIntegerField(verbose_name=_("остаток"))
    payment_method = models.CharField(
        choices=PaymentMethod.choices,
        default=PaymentMethod.CARD,
        verbose_name=_("способ оплаты"),
        max_length=128,
    )
    delivery_method = models.CharField(
        choices=DeliveryMethod.choices,
        default=DeliveryMethod.REGULAR,
        verbose_name=_("способ доставки"),
        max_length=128,
    )

    class Meta:
        verbose_name = _("предложение магазина")
        verbose_name_plural = _("предложения магазина")

    def __str__(self) -> str:
        return f"Предложение (pk={self.pk}, shop={self.shop.name!r}), product={self.product.name!r}"

market/products/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class ProductReviewForm(forms.Form):
    """Форма отзыва о товаре"""

    review_content = forms.CharField(
        max_length=512,
        label="",
        widget=forms.Textarea(attrs={"cols": "80", "rows": "3", "placeholder": _("Отзыв"), "class": "form-textarea"}),
    )

market/templates/products/famous_products.jinja2
<header class="Section-header">
    <h2 class="Section-title">{{_("Популярные товары")}}</h2>
</header>
<div class="Cards">
    {% for offer in offers %}
        <div class="Card">
            <a class="Card-picture" href="{{ url('products:product-detail', pk=offer.product.pk ) }}"><img src="{{ offer.product.preview.url }}" alt="card.jpg" style="width: 200px;"/></a>
            <div class="Card-content">
                <strong class="Card-title"><a href="{{ url('products:product-detail', pk=offer.product.pk ) }}">{{ offer.product.about }}</a>
                </strong>
                <div class="Card-description">
                    <div class="Card-cost"><span class="Card-price">{{ offer.price }}₽</span>
                    </div>
                    <div class="Card-category">{{ offer.product.category.name }}
                    </div>
                    <div class="Card-hover">
                         <form action="{{ url('cart:add_cart') }}" method="post">
                             {% csrf_token %}
                             <input type="hidden" name="offer_id" value="{{ offer.pk }}">
                             <input type="hidden" name="amount" value="1">
                             <button class="Card-btn" type="submit" onmouseover="this.style.backgroundColor='#d2e7ff';" onmouseout="this.style.backgroundColor='#ebebeb';">
                                 <img src="{{ static('assets/img/icons/card/cart.svg') }}" alt="cart.svg"/>
                             </button>
                         </form>
                         <form action="{{ url('comparison:comparison_add') }}" method="post">
                            {% csrf_token %}
                            <input type="hidden" id="product_id" name="product_id" value="{{ offer.product.pk }}">
                            <button class="Card-btn" type="submit" onmouseover="this.style.backgroundColor='#d2e7ff';" onmouseout="this.style.backgroundColor='#ebebeb';">
                                <img src="{{ static('assets/img/icons/card/change.svg') }}" alt="change.svg"/>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

market/templates/products/limited_offer.jinja2
<div class="Section-columnSection Section-columnSection_mark">
    <header class="Section-columnHeader">
        <strong class="Section-columnTitle">{{_("ОГРАНИЧЕННЫЕ ПРЕДЛОЖЕНИЯ")}}</strong>
    </header>
    <div class="Card"><a class="Card-picture" href="{{ url ('catalog:index') }}?sort=famous&desc=on&search={{ limit_offer.product.name }}"><img src="{{ limit_offer.product.preview.url }}" alt="card.jpg"/></a>
        <div class="Card-content">
            <strong class="Card-title"><a href="{{ url ('catalog:index') }}?sort=famous&desc=on&search={{ limit_offer.product.name }}">{{ limit_offer.product.name }}</a></strong>
                <div class="CountDown" data-date="{{ (limit_offer.end_date).strftime('%d.%m.%Y %H:%M') }}">
                    <div class="CountDown-block">
                        <div class="CountDown-wrap">
                            <div class="CountDown-days"></div>
                            {% trans %}
                            <span class="CountDown-label">days</span>
                        </div>
                    </div>
                    <div class="CountDown-block">
                        <div class="CountDown-wrap">
                            <div class="CountDown-hours"></div>
                            <span class="CountDown-label">hours</span>
                        </div>
                    </div>
                    <div class="CountDown-block">
                        <div class="CountDown-wrap">
                            <div class="CountDown-minutes"></div>
                            <span class="CountDown-label">mins</span>
                        </div>
                    </div>
                    <div class="CountDown-block">
                        <div class="CountDown-wrap">
                            <div class="CountDown-secs"></div>
                            <span class="CountDown-label">secs</span>
                            {% endtrans %}
                        </div>
                    </div>
                </div>
          </div>
    </div>
</div>

market/templates/products/min_offers.jinja2
<div class="wrap">
    <div class="BannersHome">
        {% for min_offer in min_offers %}
            <a class="BannersHomeBlock" href="{{ url('products:product-detail', pk=min_offer.product.pk ) }}">
                <div class="BannersHomeBlock-row">
                    <div class="BannersHomeBlock-block">
                        <strong class="BannersHomeBlock-title">{{ min_offer.product.category.name }}
                        </strong>
                        <div class="BannersHomeBlock-content">от&#32;<span class="BannersHomeBlock-price">{{ min_offer.price }}₽</span>
                        </div>
                    </div>
                    <div class="BannersHomeBlock-block">
                        <div class="BannersHomeBlock-img"><img src="{{ min_offer.product.preview.url }}" alt="category.png" />
                        </div>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
</div>

market/templates/products/offer-block.jinja2
 <div class="Order Order_anons">
    <div class="Order-personal">
        <div class="row">
            <div class="row-block">
                <a class="Order-title" href="oneorder.html">
                    {{offer.shop.name}}
                </a>
                <div class="ProductCard-cartElement" style="margin-top: 10px;">
<!--                    <a class="btn btn_primary" href="#modal_open">-->
<!--                        <img class="btn-icon" src="{{ static('assets/img/icons/card/cart_white.svg')}}" alt="cart_white.svg" />-->
<!--                        <span class="btn-content">Купить</span>-->
<!--                    </a>-->
                     <label for="push-form-offer-{{offer.pk}}" tabindex="0" class="btn btn_primary">
                        <img class="btn-icon" src="{{ static('assets/img/icons/card/cart_white.svg')}}" alt="cart_white.svg" />
                        <span class="btn-content">{{_("Купить")}} </span>
                    </label>
                </div>
            </div>
            <div class="row-block">
                <div class="Order-info Order-info_delivery">
                    <div class="Order-infoType">{{_("Тип доставки:")}}
                    </div>
                    <div class="Order-infoContent"> {{offer.get_delivery_method_display()}}
                    </div>
                </div>
                <div class="Order-info Order-info_pay">
                    <div class="Order-infoType">{{_("Оплата:")}}
                    </div>
                    <div class="Order-infoContent"> {{offer.get_payment_method_display()}}
                    </div>
                </div>
                <div class="Order-info">
                    <div class="Order-infoType">{{_("Стоимость:")}}
                    </div>
                    <div class="Order-infoContent"><span class="Order-price"> {{offer.price}} ₽</span>
                    </div>
                </div>
                <div class="Order-info">
                    <div class="Order-infoType">{{_("Остаток на складе:")}}
                    </div>
                    <div class="Order-infoContent"><span class="Order-price"> {{offer.remains}} шт</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

market/templates/products/product_details.jinja2
{% extends 'base.jinja2' %}
{% block title %} {{product.name}} {% endblock %}


{% block middle %}
    <div class="Middle Middle_top">
        <div class="Section">
            <div class="wrap">
                <div class="Product">
                    <div class="ProductCard">
                        <div class="ProductCard-look">
                            <div class="ProductCard-photo">
                            {% if product.preview %}
                                <img src="{{ product.preview.url }}" alt="{{ product.name }} preview" />
                                {% else %}
                                <p>{{_("Изображение отсутствуе")}}т</p>
                            {% endif %}
                            </div>
                            <div class="ProductCard-picts">
                                {% for picture in product.images.all() %}
                                <a class="ProductCard-pict ProductCard-pict_ACTIVE" href="{{ picture.image.url }}">
                                    <img src="{{ picture.image.url }}" alt="image {{ product.name }}" />
                                </a>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="ProductCard-desc">
                            <div class="ProductCard-header">
                                <h2 class="ProductCard-title"> {{ product.name }}
                                </h2>
                                <div class="ProductCard-info">
                                    <div class="ProductCard-cost">
                                        <div class="ProductCard-price">
                                            {% if min_price %}
                                                {{ min_price }} ₽
                                            {% else %}
                                            {{_("Предложений ещё нет")}}
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="ProductCard-text">
                                {{ product.about }}
                            </div>
                            <div class="ProductCard-cart">
                                <div class="ProductCard-cartElement ProductCard-cartElement_amount">
                                    <div class="Amount Amount_product">
                                        <form class="Amount Amount_product" action="{{ url('cart:add_cart') }}" method="post" >

                                        <button class="Amount-remove" type="button">
                                        </button>
                                            {% csrf_token %}
                                            <input class="Amount-input form-input" name="amount" type="text" value="1"/>
                                            {% for offer in product.offers.all() %}
                                                <input type="submit" id="push-form-offer-{{offer.pk}}" style="display: none;" name="offer_id" value="{{offer.pk}}" />
                                            {% endfor %}

                                        <button class="Amount-add" type="button">
                                        </button>
                                        </form>
                                    </div>
                                </div>
<!-- ----------------------------------------         В РАЗРАБОТКЕ      ------------------------------------------->
<!--                                <div class="ProductCard-cartElement">-->
<!--                                    <a class="btn btn_primary" href="#modal_open">-->
<!--                                        <img class="btn-icon" src="{{ static('assets/img/icons/card/cart_white.svg') }}" alt="cart_white.svg" />-->
<!--                                        <span class="btn-content">Купить</span>-->
<!--                                    </a>-->
<!--                                </div>-->
                                <div id="modal_open" class="my_modal">
                                    <div class="my_modal-dialog">
                                        <div class="my_modal-content">
                                            <div class="my_modal-header">
                                            {% trans %}
                                                <p class="my_modal-title">Поздравляем!</p>
                                                <a href="#" title="Закрыть модальное окно" class="close">×</a>
                                            </div>
                                            <div class="my_modal-body">
                                                <p>Товар успешно добавлен в корзину!</p>
                                            </div>
                                            {% endtrans %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="ProductCard-footer">
                                <div class="ProductCard-tags">
                                    <strong class="ProductCard-tagsTitle">{{_("Тэги")}}:
                                    </strong>
                                    {% for tag in product.tags.all() %}
                                    {{ tag.name }};
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="Tabs Tabs_default">
                        <div class="Tabs-links">
                            <a class="Tabs-link_ACTIVE Tabs-link" href="#description">
                                <span>{{_("Описание")}}</span>
                            </a>
                            <a class="Tabs-link" href="#sellers">
                                <span>{{_("Продавцы")}}</span>
                            </a>
                            <a class="Tabs-link" href="#addit">
                                <span>{{_("Характеристика")}}</span>
                            </a>
                            <a class="Tabs-link" href="#reviews">
                                <span>{{_("Отзывы")}} ({{ reviews | length }})</span>
                            </a>
                        </div>
                        <div class="Tabs-wrap">
                            <div class="Tabs-block" id="description">
                                <h2>{{ product.name }}
                                </h2>
                                {% if product.preview %}
                                <img class="pict pict_right" src="{{ product.preview.url }}" alt="{{ product.name }}_img" />
                                {% else %}
                                <p>{{_("Изображение отсутствует")}}</p>
                                {% endif %}
                                <div>
                                   {{ product.description }}
                                </div>
                                <div class="clearfix">
                                </div>
                            </div>
                            <div class="Tabs-block" id="sellers">
                                <div class="Section-content">
                                    <div class="Orders">
                                        {% for offer in product.offers.all().filter(remains__gt=0) %}
                                        {% include "products/offer-block.jinja2" %}
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            <div class="Tabs-block" id="addit">
                                <div class="Product-props">
                                    {% for parameter in product.productdetail_set.all() %}
                                    <div class="Product-prop">
                                        <strong> {{ parameter.detail.name }}
                                        </strong><span> {{ parameter.value }} </span>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>

                            {% include "products/reviews.jinja2" %}

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}